### ISSUE TITLE
V11.0.0 failing to load module for semantic-release@17.0.4

### ISSUE THREAD

**Issue by Daydreamer05** [semantic-release/gitlab-config#221]
[2:06:25 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /builds/platform/<repo>/node_modules/@semantic-release/gitlab/index.js
require() of ES modules is not supported.
require() of /builds/platform/<repo>/node_modules/@semantic-release/gitlab/index.js from /root/.npm/_npx/32/lib/node_modules/semantic-release/lib/plugins/utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /builds/platform/<repo>/node_modules/@semantic-release/gitlab/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at loadPlugin (/root/.npm/_npx/32/lib/node_modules/semantic-release/lib/plugins/utils.js:51:36)
    at /root/.npm/_npx/32/lib/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/root/.npm/_npx/32/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/root/.npm/_npx/32/lib/node_modules/semantic-release/lib/get-config.js:92:35) {
  code: 'ERR_REQUIRE_ESM'
}

I

**Comment by fgreinacher** [comment]
I'm closing this as the answer above should be enough to resolve this. Feel free to reopen if needed 👍
